[package]
name = "massive"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.rustpython-vm]
git = "https://github.com/RustPython/RustPython"
tag = "v0.2.0"
version = "0.2.0"
features = ["compiler", "threading", "importlib"]
