[package]
name = "massive"
version = "0.1.0"
edition = "2021"

[dependencies.rune]
version = "0.12.1"

[dependencies.tokio]
version = "^1"
features = ["rt-multi-thread", "fs", "macros", "io-util", "signal", "sync", "time"]
